"""add herbs and herb tags

Revision ID: 18c83e06519b
Revises: 7bc61cd31f48
Create Date: 2026-09-19 19:22:44.070847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18c83e06519b'
down_revision: Union[str, Sequence[str], None] = '7bc61cd31f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herbs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('properties', sa.String(length=255), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('effects', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_herbs_aliases_gin', 'herbs', ['aliases'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_herbs_category_id'), 'herbs', ['category_id'], unique=False)
    op.create_index('ix_herbs_channels_gin', 'herbs', ['channels'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_herbs_name'), 'herbs', ['name'], unique=True)
    op.create_table('herb_tags',
    sa.Column('herb_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('herb_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('herb_tags')
    op.drop_index(op.f('ix_herbs_name'), table_name='herbs')
    op.drop_index('ix_herbs_channels_gin', table_name='herbs', postgresql_using='gin')
    op.drop_index(op.f('ix_herbs_category_id'), table_name='herbs')
    op.drop_index('ix_herbs_aliases_gin', table_name='herbs', postgresql_using='gin')
    op.drop_table('herbs')
    # ### end Alembic commands ###
