"""add prescriptions tables

Revision ID: df288e38709a
Revises: 18c83e06519b
Create Date: 2026-09-20 10:03:16.593419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df288e38709a'
down_revision: Union[str, Sequence[str], None] = '18c83e06519b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('efficacy', sa.Text(), nullable=False),
    sa.Column('indications', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('usage_method', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescriptions_aliases_gin', 'prescriptions', ['aliases'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_prescriptions_category_id'), 'prescriptions', ['category_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_name'), 'prescriptions', ['name'], unique=True)
    op.create_table('prescription_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('herb_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('processing', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_id', 'herb_id', name='uq_prescription_ingredients_prescription_herb')
    )
    op.create_index(op.f('ix_prescription_ingredients_herb_id'), 'prescription_ingredients', ['herb_id'], unique=False)
    op.create_index(op.f('ix_prescription_ingredients_prescription_id'), 'prescription_ingredients', ['prescription_id'], unique=False)
    op.create_table('prescription_tags',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('prescription_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_tags')
    op.drop_index(op.f('ix_prescription_ingredients_prescription_id'), table_name='prescription_ingredients')
    op.drop_index(op.f('ix_prescription_ingredients_herb_id'), table_name='prescription_ingredients')
    op.drop_table('prescription_ingredients')
    op.drop_index(op.f('ix_prescriptions_name'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_category_id'), table_name='prescriptions')
    op.drop_index('ix_prescriptions_aliases_gin', table_name='prescriptions', postgresql_using='gin')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
